name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: theasp/clojurescript-nodejs:shadow-cljs-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Download dependencies
        run: shadow-cljs npm-deps && npm install

      - name: Run Clojure test
        run: |
          shadow-cljs compile test
          node static/tests.js
